// <auto-generated />
using System;
using MakeFriendSolution.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakeFriendSolution.Migrations
{
    [DbContext(typeof(MakeFriendDbContext))]
    [Migration("20210110113111_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MakeFriendSolution.Models.Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorizeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnauthorizeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Accesses");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AtmosphereLike")
                        .HasColumnType("int");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Body")
                        .HasColumnType("int");

                    b.Property<int>("Character")
                        .HasColumnType("int");

                    b.Property<int>("Cook")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrinkBeer")
                        .HasColumnType("int");

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("FavoriteMovie")
                        .HasColumnType("int");

                    b.Property<int>("FindPeople")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Game")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsInfoUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Job")
                        .HasColumnType("int");

                    b.Property<int>("LifeStyle")
                        .HasColumnType("int");

                    b.Property<int>("LikePet")
                        .HasColumnType("int");

                    b.Property<int>("LikeTechnology")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("Marriage")
                        .HasColumnType("int");

                    b.Property<int>("MostValuable")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfFiends")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NumberOfImages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NumberOfLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NumberOfPasswordConfirmations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("PasswordForgottenCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("PasswordForgottenPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaySport")
                        .HasColumnType("int");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Shopping")
                        .HasColumnType("int");

                    b.Property<int>("Smoking")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Target")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Travel")
                        .HasColumnType("int");

                    b.Property<int>("TypeAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 1, 10, 18, 31, 10, 998, DateTimeKind.Local).AddTicks(1911));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c96d"),
                            AtmosphereLike = 4,
                            AvatarPath = "tam.jpg",
                            Body = 2,
                            Character = 2,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 3,
                            Education = 3,
                            Email = "tam@gmail.com",
                            FavoriteMovie = 9,
                            FindPeople = 0,
                            FullName = "Nguyễn Thành Tâm",
                            Game = 0,
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 6,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 2,
                            MostValuable = 5,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "admin",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 1,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 0,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Admin",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c967"),
                            AtmosphereLike = 3,
                            AvatarPath = "nhung2.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "nhung@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Nguyễn Huyền Nhung",
                            Game = 0,
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 6,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 3,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0369875463",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 1,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "nhung2",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c96e"),
                            AtmosphereLike = 0,
                            AvatarPath = "vuong.jpg",
                            Body = 3,
                            Character = 3,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 1,
                            Education = 4,
                            Email = "vuong@gmail.com",
                            FavoriteMovie = 7,
                            FindPeople = 0,
                            FullName = "Nguyên Vương",
                            Game = 0,
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 1,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 38,
                            Marriage = 3,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 2,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Vương, rất vui khi được làm quen với bạn",
                            Target = 3,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "vuong",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c96f"),
                            AtmosphereLike = 3,
                            AvatarPath = "hieu.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "hieu@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Võ Minh Hiếu",
                            Game = 0,
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "hieu",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c965"),
                            AtmosphereLike = 3,
                            AvatarPath = "tien.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "tien@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Lê Minh Tiến",
                            Game = 0,
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "tien",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c961"),
                            AtmosphereLike = 3,
                            AvatarPath = "dinh.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "dinh@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Lê Kim Đỉnh",
                            Game = 0,
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Dinh",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c962"),
                            AtmosphereLike = 3,
                            AvatarPath = "dat.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "dat@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Hồ Quốc Đạt",
                            Game = 0,
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Dat",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c963"),
                            AtmosphereLike = 3,
                            AvatarPath = "son.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "son@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Phan Sơn",
                            Game = 0,
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Son",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c964"),
                            AtmosphereLike = 3,
                            AvatarPath = "duc.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "duc@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Trí Đức",
                            Game = 0,
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Duc",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c966"),
                            AtmosphereLike = 3,
                            AvatarPath = "nhung.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "nhung1@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Gia Nhung",
                            Game = 0,
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "GiaNhung",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c968"),
                            AtmosphereLike = 3,
                            AvatarPath = "diem.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "diem@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Kiều Diễm",
                            Game = 0,
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Diem",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c969"),
                            AtmosphereLike = 3,
                            AvatarPath = "han.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "han@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Gia Hân",
                            Game = 0,
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Han",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c977"),
                            AtmosphereLike = 3,
                            AvatarPath = "mai.jpg",
                            Body = 2,
                            Character = 1,
                            Cook = 0,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "mai@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Xuân Maiii",
                            Game = 0,
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            LikePet = 0,
                            LikeTechnology = 0,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfFiends = 0,
                            NumberOfImages = 0,
                            NumberOfLikes = 0,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            PlaySport = 0,
                            Religion = 0,
                            Role = 0,
                            Shopping = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            Travel = 0,
                            TypeAccount = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Mai",
                            Weight = 65
                        });
                });

            modelBuilder.Entity("MakeFriendSolution.Models.BlockUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLock")
                        .HasColumnType("bit");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("BlockUsers");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCalculated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDisplay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Dáng người",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Học vấn",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Phong cách sống",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 4,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Điều quan trọng nhất",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 5,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Tôn giáo",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 6,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Thể loại phim ưa thích",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 7,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Nhạc ưa thích",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 8,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Bầu không khí ưa thích",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 9,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Đi mua sắm",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 10,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Đi du lịch",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 11,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Chơi game",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 12,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Nấu ăn",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 13,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Công nghệ",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 14,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Thú cưng",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 15,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Chơi thể thao",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 16,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Hút thuốc",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 17,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = true,
                            Name = "Uống rượu bia",
                            WeightRate = 1.0
                        },
                        new
                        {
                            Id = 18,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = false,
                            Name = "Giới tính",
                            WeightRate = 0.0
                        },
                        new
                        {
                            Id = 19,
                            Delete = false,
                            IsCalculated = true,
                            IsDisplay = false,
                            Name = "Nhóm tuổi",
                            WeightRate = 0.0
                        });
                });

            modelBuilder.Entity("MakeFriendSolution.Models.FeatureDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeatureDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Nhỏ nhắn",
                            FeatureId = 1,
                            Weight = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Mảnh mai",
                            FeatureId = 1,
                            Weight = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Cân đối",
                            FeatureId = 1,
                            Weight = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Mũm mĩm",
                            FeatureId = 1,
                            Weight = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "Cao lớn",
                            FeatureId = 1,
                            Weight = 5
                        },
                        new
                        {
                            Id = 6,
                            Content = "Vạm vỡ",
                            FeatureId = 1,
                            Weight = 6
                        },
                        new
                        {
                            Id = 7,
                            Content = "Phổ thông",
                            FeatureId = 2,
                            Weight = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Trung cấp",
                            FeatureId = 2,
                            Weight = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "Cao đẳng",
                            FeatureId = 2,
                            Weight = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "Đại học",
                            FeatureId = 2,
                            Weight = 4
                        },
                        new
                        {
                            Id = 11,
                            Content = "Cao học",
                            FeatureId = 2,
                            Weight = 5
                        },
                        new
                        {
                            Id = 12,
                            Content = "Trên cao học",
                            FeatureId = 2,
                            Weight = 6
                        },
                        new
                        {
                            Id = 13,
                            Content = "An nhàn",
                            FeatureId = 3,
                            Weight = 1
                        },
                        new
                        {
                            Id = 14,
                            Content = "Giản dị",
                            FeatureId = 3,
                            Weight = 2
                        },
                        new
                        {
                            Id = 15,
                            Content = "Lạc quan",
                            FeatureId = 3,
                            Weight = 3
                        },
                        new
                        {
                            Id = 16,
                            Content = "Lành mạnh",
                            FeatureId = 3,
                            Weight = 4
                        },
                        new
                        {
                            Id = 17,
                            Content = "Năng động",
                            FeatureId = 3,
                            Weight = 5
                        },
                        new
                        {
                            Id = 18,
                            Content = "Tình cảm",
                            FeatureId = 3,
                            Weight = 6
                        },
                        new
                        {
                            Id = 19,
                            Content = "Tự do",
                            FeatureId = 3,
                            Weight = 7
                        },
                        new
                        {
                            Id = 20,
                            Content = "Sức khỏe",
                            FeatureId = 4,
                            Weight = 1
                        },
                        new
                        {
                            Id = 21,
                            Content = "Thời gian",
                            FeatureId = 4,
                            Weight = 2
                        },
                        new
                        {
                            Id = 22,
                            Content = "Bạn bè",
                            FeatureId = 4,
                            Weight = 3
                        },
                        new
                        {
                            Id = 23,
                            Content = "Bạn đời",
                            FeatureId = 4,
                            Weight = 4
                        },
                        new
                        {
                            Id = 24,
                            Content = "Gia đình",
                            FeatureId = 4,
                            Weight = 5
                        },
                        new
                        {
                            Id = 25,
                            Content = "Sự nghiệp",
                            FeatureId = 4,
                            Weight = 6
                        },
                        new
                        {
                            Id = 26,
                            Content = "Niềm vui mỗi ngày",
                            FeatureId = 4,
                            Weight = 7
                        },
                        new
                        {
                            Id = 27,
                            Content = "Không có đạo",
                            FeatureId = 5,
                            Weight = 1
                        },
                        new
                        {
                            Id = 28,
                            Content = "Thiên Chúa giáo",
                            FeatureId = 5,
                            Weight = 2
                        },
                        new
                        {
                            Id = 29,
                            Content = "Phật giáo",
                            FeatureId = 5,
                            Weight = 3
                        },
                        new
                        {
                            Id = 100,
                            Content = "Tin Lành",
                            FeatureId = 5,
                            Weight = 4
                        },
                        new
                        {
                            Id = 101,
                            Content = "Đạo khác",
                            FeatureId = 5,
                            Weight = 5
                        },
                        new
                        {
                            Id = 30,
                            Content = "Hành động",
                            FeatureId = 6,
                            Weight = 1
                        },
                        new
                        {
                            Id = 31,
                            Content = "Khoa học viễn tưởng",
                            FeatureId = 6,
                            Weight = 2
                        },
                        new
                        {
                            Id = 32,
                            Content = "Chiến tranh",
                            FeatureId = 6,
                            Weight = 3
                        },
                        new
                        {
                            Id = 33,
                            Content = "Chiến tranh",
                            FeatureId = 6,
                            Weight = 4
                        },
                        new
                        {
                            Id = 34,
                            Content = "Cổ trang",
                            FeatureId = 6,
                            Weight = 5
                        },
                        new
                        {
                            Id = 35,
                            Content = "Hài hước",
                            FeatureId = 6,
                            Weight = 6
                        },
                        new
                        {
                            Id = 36,
                            Content = "Kinh dị",
                            FeatureId = 6,
                            Weight = 7
                        },
                        new
                        {
                            Id = 37,
                            Content = "Lãng mạn",
                            FeatureId = 6,
                            Weight = 8
                        },
                        new
                        {
                            Id = 38,
                            Content = "Hoạt hình",
                            FeatureId = 6,
                            Weight = 9
                        },
                        new
                        {
                            Id = 39,
                            Content = "Nhạc trẻ",
                            FeatureId = 7,
                            Weight = 1
                        },
                        new
                        {
                            Id = 40,
                            Content = "Pop",
                            FeatureId = 7,
                            Weight = 2
                        },
                        new
                        {
                            Id = 41,
                            Content = "Dance",
                            FeatureId = 7,
                            Weight = 3
                        },
                        new
                        {
                            Id = 42,
                            Content = "Rap - Hip hop",
                            FeatureId = 7,
                            Weight = 4
                        },
                        new
                        {
                            Id = 43,
                            Content = "Nhạc Bolero",
                            FeatureId = 7,
                            Weight = 5
                        },
                        new
                        {
                            Id = 44,
                            Content = "Tĩnh lặng",
                            FeatureId = 8,
                            Weight = 1
                        },
                        new
                        {
                            Id = 45,
                            Content = "Êm đềm",
                            FeatureId = 8,
                            Weight = 2
                        },
                        new
                        {
                            Id = 46,
                            Content = "Bình yên",
                            FeatureId = 8,
                            Weight = 3
                        },
                        new
                        {
                            Id = 47,
                            Content = "Vui tươi",
                            FeatureId = 8,
                            Weight = 4
                        },
                        new
                        {
                            Id = 48,
                            Content = "Náo nhiệt",
                            FeatureId = 8,
                            Weight = 5
                        },
                        new
                        {
                            Id = 49,
                            Content = "Ít khi đi",
                            FeatureId = 9,
                            Weight = 1
                        },
                        new
                        {
                            Id = 50,
                            Content = "Thỉnh thoảng",
                            FeatureId = 9,
                            Weight = 2
                        },
                        new
                        {
                            Id = 51,
                            Content = "Thường xuyên",
                            FeatureId = 9,
                            Weight = 3
                        },
                        new
                        {
                            Id = 52,
                            Content = "Ít khi đi",
                            FeatureId = 10,
                            Weight = 1
                        },
                        new
                        {
                            Id = 53,
                            Content = "Thỉnh thoảng",
                            FeatureId = 10,
                            Weight = 2
                        },
                        new
                        {
                            Id = 54,
                            Content = "Thường xuyên",
                            FeatureId = 10,
                            Weight = 3
                        },
                        new
                        {
                            Id = 56,
                            Content = "Không chơi game",
                            FeatureId = 11,
                            Weight = 1
                        },
                        new
                        {
                            Id = 57,
                            Content = "Thỉnh thoảng",
                            FeatureId = 11,
                            Weight = 2
                        },
                        new
                        {
                            Id = 58,
                            Content = "Thường xuyên",
                            FeatureId = 11,
                            Weight = 3
                        },
                        new
                        {
                            Id = 59,
                            Content = "Nghiện game",
                            FeatureId = 11,
                            Weight = 4
                        },
                        new
                        {
                            Id = 60,
                            Content = "Không nấu ăn",
                            FeatureId = 12,
                            Weight = 1
                        },
                        new
                        {
                            Id = 61,
                            Content = "Ít nấu ăn",
                            FeatureId = 12,
                            Weight = 2
                        },
                        new
                        {
                            Id = 62,
                            Content = "Thỉnh thoảng",
                            FeatureId = 12,
                            Weight = 3
                        },
                        new
                        {
                            Id = 63,
                            Content = "Thường xuyên",
                            FeatureId = 12,
                            Weight = 4
                        },
                        new
                        {
                            Id = 64,
                            Content = "Bình thường",
                            FeatureId = 13,
                            Weight = 1
                        },
                        new
                        {
                            Id = 65,
                            Content = "Chỉ theo dõi",
                            FeatureId = 13,
                            Weight = 2
                        },
                        new
                        {
                            Id = 66,
                            Content = "Tính đồ công nghệ",
                            FeatureId = 13,
                            Weight = 3
                        },
                        new
                        {
                            Id = 67,
                            Content = "Không thích",
                            FeatureId = 14,
                            Weight = 1
                        },
                        new
                        {
                            Id = 68,
                            Content = "Nuôi cho vui",
                            FeatureId = 14,
                            Weight = 2
                        },
                        new
                        {
                            Id = 69,
                            Content = "Thích thú cưng",
                            FeatureId = 14,
                            Weight = 3
                        },
                        new
                        {
                            Id = 70,
                            Content = "Ít khi chơi",
                            FeatureId = 15,
                            Weight = 1
                        },
                        new
                        {
                            Id = 71,
                            Content = "Thỉnh thoảng",
                            FeatureId = 15,
                            Weight = 2
                        },
                        new
                        {
                            Id = 72,
                            Content = "Thường xuyên",
                            FeatureId = 15,
                            Weight = 3
                        },
                        new
                        {
                            Id = 73,
                            Content = "Không hút thuốc",
                            FeatureId = 16,
                            Weight = 1
                        },
                        new
                        {
                            Id = 74,
                            Content = "Hút xã giao",
                            FeatureId = 16,
                            Weight = 2
                        },
                        new
                        {
                            Id = 75,
                            Content = "Hút nhiều",
                            FeatureId = 16,
                            Weight = 3
                        },
                        new
                        {
                            Id = 76,
                            Content = "Không uống",
                            FeatureId = 17,
                            Weight = 1
                        },
                        new
                        {
                            Id = 77,
                            Content = "Uống xã giao",
                            FeatureId = 17,
                            Weight = 2
                        },
                        new
                        {
                            Id = 78,
                            Content = "Uống nhiều",
                            FeatureId = 17,
                            Weight = 3
                        },
                        new
                        {
                            Id = 79,
                            Content = "Khác giới",
                            FeatureId = 18,
                            Weight = 1
                        },
                        new
                        {
                            Id = 80,
                            Content = "Cùng giới",
                            FeatureId = 18,
                            Weight = -1
                        },
                        new
                        {
                            Id = 81,
                            Content = "Dưới_18_Tuổi",
                            FeatureId = 19,
                            Weight = 1
                        },
                        new
                        {
                            Id = 82,
                            Content = "Từ_18_Đến_25",
                            FeatureId = 19,
                            Weight = 2
                        },
                        new
                        {
                            Id = 83,
                            Content = "Từ_25_Đến_30",
                            FeatureId = 19,
                            Weight = 3
                        },
                        new
                        {
                            Id = 84,
                            Content = "Từ_31_Đến_40",
                            FeatureId = 19,
                            Weight = 4
                        },
                        new
                        {
                            Id = 85,
                            Content = "Từ_41_Đến_50",
                            FeatureId = 19,
                            Weight = 5
                        },
                        new
                        {
                            Id = 86,
                            Content = "Trên_50",
                            FeatureId = 19,
                            Weight = 6
                        });
                });

            modelBuilder.Entity("MakeFriendSolution.Models.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.HaveMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("HaveMessages");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.LikeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("UserId");

                    b.ToTable("LikeImages");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.SimilarityFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 1, 10, 18, 31, 11, 24, DateTimeKind.Local).AddTicks(134));

                    b.HasKey("Id");

                    b.ToTable("SimilariryFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UpdatedAt = new DateTime(2021, 1, 10, 18, 31, 11, 31, DateTimeKind.Local).AddTicks(8622)
                        });
                });

            modelBuilder.Entity("MakeFriendSolution.Models.SimilarityScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.ToTable("SimilarityScores");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.ThumbnailImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOflikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Image title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ThumbnailImages");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.UserFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit");

                    b.Property<int>("FeatureDetailId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FeatureDetailId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFeatures");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.BlockUser", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "FromUser")
                        .WithMany("BlockedByUsers")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "ToUser")
                        .WithMany("UserWasBlock")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.Favorite", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "FromUser")
                        .WithMany("Favorited")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "ToUser")
                        .WithMany("BeingFavoritedBy")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.FeatureDetail", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.Feature", "Feature")
                        .WithMany("FeatureDetails")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.Follow", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "FromUser")
                        .WithMany("Followed")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "ToUser")
                        .WithMany("BeingFollowedBy")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.HaveMessage", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "Receiver")
                        .WithMany("ReceiveMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "Sender")
                        .WithMany("SendMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.LikeImage", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.ThumbnailImage", "Image")
                        .WithMany("LikeImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.SimilarityScore", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "FromUser")
                        .WithMany("SimilarityScores")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.ThumbnailImage", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "User")
                        .WithMany("ThumbnailImages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.UserFeature", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.FeatureDetail", "FeatureDetail")
                        .WithMany("UserFeatures")
                        .HasForeignKey("FeatureDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.Feature", "Feature")
                        .WithMany("UserFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "User")
                        .WithMany("HaveFeatures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
