// <auto-generated />
using System;
using MakeFriendSolution.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakeFriendSolution.Migrations
{
    [DbContext(typeof(MakeFriendDbContext))]
    partial class MakeFriendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MakeFriendSolution.Models.Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorizeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnauthorizeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Accesses");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AtmosphereLike")
                        .HasColumnType("int");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Body")
                        .HasColumnType("int");

                    b.Property<int>("Character")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrinkBeer")
                        .HasColumnType("int");

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("FavoriteMovie")
                        .HasColumnType("int");

                    b.Property<int>("FindPeople")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsInfoUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Job")
                        .HasColumnType("int");

                    b.Property<int>("LifeStyle")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("Marriage")
                        .HasColumnType("int");

                    b.Property<int>("MostValuable")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPasswordConfirmations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("PasswordForgottenCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("PasswordForgottenPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Smoking")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Target")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c96d"),
                            AtmosphereLike = 3,
                            AvatarPath = "Tam.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "tam@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Nguyễn Thành Tâm",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "admin",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Admin",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c967"),
                            AtmosphereLike = 3,
                            AvatarPath = "nhung2.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "nhung@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Nguyễn Huyền Nhung",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 5,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 3,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0369875463",
                            Religion = 0,
                            Role = 1,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "nhung2",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c96e"),
                            AtmosphereLike = 0,
                            AvatarPath = "vuong.jpg",
                            Body = 3,
                            Character = 3,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 4,
                            Email = "vuong@gmail.com",
                            FavoriteMovie = 7,
                            FindPeople = 0,
                            FullName = "Nguyên Vương",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 1,
                            Location = 38,
                            Marriage = 2,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 2,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Vương, rất vui khi được làm quen với bạn",
                            Target = 3,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "vuong",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c96f"),
                            AtmosphereLike = 3,
                            AvatarPath = "hieu.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "hieu@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Võ Minh Hiếu",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "hieu",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c965"),
                            AtmosphereLike = 3,
                            AvatarPath = "tien.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "tien@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Lê Minh Tiến",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "tien",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c961"),
                            AtmosphereLike = 3,
                            AvatarPath = "dinh.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "dinh@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Lê Kim Đỉnh",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Dinh",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c962"),
                            AtmosphereLike = 3,
                            AvatarPath = "dat.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "dat@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Hồ Quốc Đạt",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Dat",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c963"),
                            AtmosphereLike = 3,
                            AvatarPath = "son.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "son@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Phan Sơn",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Son",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c964"),
                            AtmosphereLike = 3,
                            AvatarPath = "duc.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "duc@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Trí Đức",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Duc",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c966"),
                            AtmosphereLike = 3,
                            AvatarPath = "nhung.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "nhung1@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Gia Nhung",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "GiaNhung",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c968"),
                            AtmosphereLike = 3,
                            AvatarPath = "diem.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "diem@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Kiều Diễm",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Diem",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c969"),
                            AtmosphereLike = 3,
                            AvatarPath = "han.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "han@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Gia Hân",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Han",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ec826af8-0310-48cf-8a14-da11bdb1c977"),
                            AtmosphereLike = 3,
                            AvatarPath = "mai.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "mai@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Xuân Maiii",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Mai",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("55a1618f-abd8-4972-ae02-b9cf1ab2e6d9"),
                            AtmosphereLike = 3,
                            AvatarPath = "nhung2.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "nhung1@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Nguyễn Huyền Nhung2",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 5,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 3,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0369875463",
                            Religion = 0,
                            Role = 1,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "nhung2",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("8f8c15dd-9831-491e-bc5d-2786a510baa4"),
                            AtmosphereLike = 0,
                            AvatarPath = "vuong.jpg",
                            Body = 3,
                            Character = 3,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 4,
                            Email = "vuong2@gmail.com",
                            FavoriteMovie = 7,
                            FindPeople = 0,
                            FullName = "Nguyên Vương2",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 1,
                            Location = 38,
                            Marriage = 2,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 2,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Vương, rất vui khi được làm quen với bạn",
                            Target = 3,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "vuong",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("55816cde-5a3a-4769-a5c2-80cf5f3cee47"),
                            AtmosphereLike = 3,
                            AvatarPath = "hieu.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "hieu2@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Võ Minh Hiếu2",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "hieu",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("38f986e0-2549-4c27-ac66-55916422af97"),
                            AtmosphereLike = 3,
                            AvatarPath = "tien.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "tien@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Lê Minh Tiến2",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "tien",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("d7b489b4-368b-46da-9359-52b00fe16867"),
                            AtmosphereLike = 3,
                            AvatarPath = "dinh.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "dinh2@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Lê Kim Đỉnh2",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Dinh",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("569abcf7-cb03-4d54-b006-e239eb30f900"),
                            AtmosphereLike = 3,
                            AvatarPath = "dat.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "dat2@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Hồ Quốc Đạt2",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Dat",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("d2527d31-99b5-4810-b12c-ba0f080de179"),
                            AtmosphereLike = 3,
                            AvatarPath = "son.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "son2@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Phan Sơn2",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Son",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("494f726a-36c3-49d7-b0b9-ebfa41bc73dc"),
                            AtmosphereLike = 3,
                            AvatarPath = "duc.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "duc2@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Trí Đức2",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Duc",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("ffbae934-b3a7-4897-8099-f64dcee55d95"),
                            AtmosphereLike = 3,
                            AvatarPath = "nhung.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "nhung2@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Gia Nhung2",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "GiaNhung",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("a142e55c-fd1f-4b9e-9dd7-fff4177a3136"),
                            AtmosphereLike = 3,
                            AvatarPath = "diem.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "diem2@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Kiều Diễm2",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Diem",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("99657a02-5101-44f8-b96e-15871441f20e"),
                            AtmosphereLike = 3,
                            AvatarPath = "han.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "han2@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Gia Hân2",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Han",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("be2a936b-c612-4877-a6cd-f3291ded0235"),
                            AtmosphereLike = 3,
                            AvatarPath = "mai.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "mai2@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Xuân Maiii2",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Mai",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("f5fc2cd9-d6b0-4694-88ec-822dce666481"),
                            AtmosphereLike = 3,
                            AvatarPath = "nhung2.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "nhung3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Nguyễn Huyền Nhung3",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 5,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 3,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0369875463",
                            Religion = 0,
                            Role = 1,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "nhung2",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("2a7d6946-4da4-44a3-8d6a-ec06368a00b5"),
                            AtmosphereLike = 0,
                            AvatarPath = "vuong.jpg",
                            Body = 3,
                            Character = 3,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 4,
                            Email = "vuong3@gmail.com",
                            FavoriteMovie = 7,
                            FindPeople = 0,
                            FullName = "Nguyên Vương3",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 1,
                            Location = 38,
                            Marriage = 2,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 2,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Vương, rất vui khi được làm quen với bạn",
                            Target = 3,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "vuong",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("70599229-5f70-43ff-939a-771c71977314"),
                            AtmosphereLike = 3,
                            AvatarPath = "hieu.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "hieu3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Võ Minh Hiếu3",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "hieu",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("b58df0cd-e276-41fe-9990-2a0290d74fb2"),
                            AtmosphereLike = 3,
                            AvatarPath = "tien.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "tien3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Lê Minh Tiến3",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "tien",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("0b28d639-40e8-40a1-856f-95b87d796d80"),
                            AtmosphereLike = 3,
                            AvatarPath = "dinh.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "dinh3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Lê Kim Đỉnh3",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Dinh",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("508c0a22-5c4a-49fc-abb3-27989f0dacf9"),
                            AtmosphereLike = 3,
                            AvatarPath = "dat.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "dat3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Hồ Quốc Đạt3",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Dat",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("b6b1aeb7-4d79-40cc-9f89-ca5a11b10d01"),
                            AtmosphereLike = 3,
                            AvatarPath = "son.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "son3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Phan Sơn3",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Son",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("e761d884-1b1d-4d46-b759-1ccd3fc05a02"),
                            AtmosphereLike = 3,
                            AvatarPath = "duc.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "duc3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 0,
                            FullName = "Trí Đức3",
                            Gender = 1,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Duc",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("277cc9e0-85d3-43aa-8fed-924fcd616632"),
                            AtmosphereLike = 3,
                            AvatarPath = "nhung.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "nhung3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Gia Nhung3",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "GiaNhung",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("be3a8b41-735e-417f-a2d6-8a1ce492cab0"),
                            AtmosphereLike = 3,
                            AvatarPath = "diem.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "diem3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Kiều Diễm3",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Diem",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("b96b2030-11f3-48ab-bca0-e96c78a8a3e6"),
                            AtmosphereLike = 3,
                            AvatarPath = "han.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "han3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Gia Hân3",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Han",
                            Weight = 65
                        },
                        new
                        {
                            Id = new Guid("dba9f471-d67e-4e01-b9d8-b5facfdd782d"),
                            AtmosphereLike = 3,
                            AvatarPath = "mai.jpg",
                            Body = 2,
                            Character = 1,
                            CreatedAt = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrinkBeer = 4,
                            Education = 2,
                            Email = "mai3@gmail.com",
                            FavoriteMovie = 11,
                            FindPeople = 1,
                            FullName = "Xuân Maiii3",
                            Gender = 0,
                            Height = 170,
                            IsInfoUpdated = true,
                            Job = 7,
                            LifeStyle = 3,
                            Location = 37,
                            Marriage = 1,
                            MostValuable = 2,
                            NumberOfPasswordConfirmations = 0,
                            PassWord = "1111",
                            PasswordForgottenPeriod = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0396925225",
                            Religion = 0,
                            Role = 0,
                            Smoking = 1,
                            Status = 0,
                            Summary = "Tôi là Tâm, rất vui khi được làm quen với bạn",
                            Target = 4,
                            Title = "Thông tin của tôi",
                            TypeAccount = 0,
                            UserName = "Mai",
                            Weight = 65
                        });
                });

            modelBuilder.Entity("MakeFriendSolution.Models.BlockUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("BlockUsers");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.HaveMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("HaveMessages");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.LikeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("UserId");

                    b.ToTable("LikeImages");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.ThumbnailImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Image title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ThumbnailImages");
                });

            modelBuilder.Entity("MakeFriendSolution.Models.BlockUser", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "FromUser")
                        .WithMany("BlockedByUsers")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "ToUser")
                        .WithMany("UserWasBlock")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.Favorite", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "FromUser")
                        .WithMany("Favorited")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "ToUser")
                        .WithMany("BeingFavoritedBy")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.Follow", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "FromUser")
                        .WithMany("Followed")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "ToUser")
                        .WithMany("BeingFollowedBy")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.HaveMessage", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "Receiver")
                        .WithMany("ReceiveMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "Sender")
                        .WithMany("SendMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.LikeImage", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.ThumbnailImage", "Image")
                        .WithMany("LikeImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MakeFriendSolution.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakeFriendSolution.Models.ThumbnailImage", b =>
                {
                    b.HasOne("MakeFriendSolution.Models.AppUser", "User")
                        .WithMany("ThumbnailImages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
