using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MakeFriendSolution.Models.Enum
{
    public enum ELocation
    {
        AnGiang,
        Bà_Rịa_Vũng_Tàu,
        Bắc_Giang,
        Bắc_Kạn,
        Bạc_Liêu,
        Bắc_Ninh,
        Bến_Tre,
        Bình_Định,
        Bình_Dương,
        Bình_Phước,
        Bình_Thuận,
        Cà_Mau,
        Cao_Bằng,
        Đắk_Lắk,
        Đắk_Nông,
        Điện_Biên,
        Đồng_Nai,
        Đồng_Tháp,
        Gia_Lai,
        Hà_Giang,
        Hà_Nam,
        Hà_Tĩnh,
        Hải_Dương,
        Hậu_Giang,
        Hòa_Bình,
        Hưng_Yên,
        Khánh_Hòa,
        Kiên_Giang,
        Kon_Tum,
        Lai_Châu,
        Lâm_Đồng,
        Lạng_Sơn,
        Lào_Cai,
        Long_An,
        Nam_Định,
        Nghệ_An,
        Ninh_Bình,
        Ninh_Thuận,
        Phú_Thọ,
        Quảng_Bình,
        Quảng_Nam,
        Quảng_Ngãi,
        Quảng_Ninh,
        Quảng_Trị,
        Sóc_Trăng,
        Sơn_La,
        Tây_Ninh,
        Thái_Bình,
        Thái_Nguyên,
        Thanh_Hóa,
        Thừa_Thiên_Huế,
        Tiền_Giang,
        Trà_Vinh,
        Tuyên_Quang,
        Vĩnh_Long,
        Vĩnh_Phúc,
        Yên_Bái,
        Phú_Yên,
        Cần_Thơ,
        Đà_Nẵng,
        Hải_Phòng,
        Hà_Nội,
        TP_HCM
    }
}